language: node_js

node_js:
- '10.6.0'
- '6'
- '7'
- '8'
- '9'

sudo: false

env:
  global:
    secure: CvWvWn6pDIBUUdi3gVmvLSbgojqqG0NDhKQv9k6dg4U/1wUT0nhaiFsQAeCiFxCv6fclMA/oLhz4O6TUMBDXLUGXrKixu5Nk4kzrIthjbbukXoZ4K//3H/r9M3Zas21StS25dMszryhcvH5CbnO4DQqaV5cXlg9uyVru3k97q4U=
