language: node_js

node_js:
- '10.6.0'
- '6'
- '7'
- '8'
- '9'

sudo: false

# Allow greenkeeper to commit package-lock.json, greenkeeper-lockfile-upload
# will run only on the first listed node_js version:
before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

env:
  global:
    secure: CvWvWn6pDIBUUdi3gVmvLSbgojqqG0NDhKQv9k6dg4U/1wUT0nhaiFsQAeCiFxCv6fclMA/oLhz4O6TUMBDXLUGXrKixu5Nk4kzrIthjbbukXoZ4K//3H/r9M3Zas21StS25dMszryhcvH5CbnO4DQqaV5cXlg9uyVru3k97q4U=
